pool:
  vmImage: Azure Pipelines
variables:
  public_ip: '"[\'34.226.121.50\']"'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      sed -i "s/^ALLOWED_HOSTS = \['.*'\]/ALLOWED_HOSTS = $(public_ip)/" settings.py
    workingDirectory: 'webpro'
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      pip install -r requirements.txt
    workingDirectory: 'webpro'
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'manage.py'
- task: Docker@2
  inputs:
    containerRegistry: 'mydockerhub'
    repository: '1234si/pythonapp'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: '$(Build.BuildNumber)'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      docker-compose.yml
      nginx.conf
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
