# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
 
- task: CmdLine@2
  inputs:
    script: 'pip install -r requirements.txt'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      sed -i "s/^ALLOWED_HOSTS = \['.*'\]/ALLOWED_HOSTS = $(public_ip)/" settings.py
    workingDirectory: '$(Build.SourcesDirectory)/webpro'
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'manage.py'
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-sn'
    repository: '1234si/pythonapp'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: '$(Build.BuildNumber)'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'Build.SourcesDirectory'
    Contents: '**'
    TargetFolder: 'Build.ArtifactStagingDirectory'