version: "3.8"
services:
    app:
    environment:
      - TAG='0'
      image: 1234si/pythonapp:${TAG}
      ports:
          - 8002:8002
    nginx:
         image: nginx
         ports:
           - 80:80
         volumes:
           - ./nginx.conf:/etc/nginx/nginx.conf
         depends_on:
           - app
